services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prahsys-laravel-perimeter
    container_name: prahsys-laravel-perimeter
    restart: unless-stopped
    working_dir: /var/www/laravel-app
    # Using systemd as PID 1
    init: false
    # No command override - using systemd init from Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/package
    networks:
      - prahsys
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/laravel-app/database/database.sqlite
      - PERIMETER_FAIL2BAN_ENABLED=true
      - DEBIAN_FRONTEND=noninteractive
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - SYS_ADMIN  # Required for system-level security tools
      - SYS_PTRACE # Required for process tracing
      - NET_ADMIN  # Required for network monitoring
    security_opt:
      - apparmor:unconfined
      - seccomp=unconfined  # Required for systemd
    privileged: true  # Required for systemd

networks:
  prahsys:
    driver: bridge