# Falco configuration for container
# Created by Laravel Perimeter

driver:
  enabled: false

stdout_output:
  enabled: true

file_output:
  enabled: true
  keep_alive: true
  filename: /var/log/falco.log