<?php

namespace Prahsys\Perimeter\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Prahsys\Perimeter\Models\SecurityEvent;
use Prahsys\Perimeter\Models\SecurityScan;

class PerimeterCleanupTest extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'perimeter:cleanup-test 
                            {--dry-run : Show what would be deleted without actually deleting}
                            {--force : Skip confirmation prompt}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Clean up test monitoring events and scans generated by perimeter:test-monitoring';

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $dryRun = $this->option('dry-run');
        $force = $this->option('force');

        $this->info('🧹 Perimeter Test Cleanup');
        $this->info('Looking for all test events and scans');

        if ($dryRun) {
            $this->warn('DRY RUN MODE: Nothing will be deleted');
        }

        $this->newLine();

        // Find test security events
        $testEvents = SecurityEvent::where(function ($query) {
            $query->where('service', 'perimeter-test')
                ->orWhere('details', 'LIKE', '%"test":true%')
                ->orWhere('description', 'LIKE', 'TEST ALERT:%');
        })
            ->get();

        // Find test security scans
        $testScans = SecurityScan::where(function ($query) {
            $query->where('scan_type', 'monitoring_test')
                ->orWhere('command', 'perimeter:test-monitoring')
                ->orWhere('scan_details', 'LIKE', '%"test":true%');
        })
            ->get();

        $this->info("Found {$testEvents->count()} test events");
        $this->info("Found {$testScans->count()} test scans");

        if ($testEvents->isEmpty() && $testScans->isEmpty()) {
            $this->info('No test data found to clean up');

            return 0;
        }

        if ($dryRun) {
            $this->newLine();
            $this->info('Test Events to be deleted:');
            $this->table(
                ['ID', 'Type', 'Severity', 'Description', 'Created'],
                $testEvents->map(function ($event) {
                    return [
                        $event->id,
                        $event->type,
                        $event->severity,
                        substr($event->description, 0, 50).'...',
                        $event->created_at->format('Y-m-d H:i:s'),
                    ];
                })->toArray()
            );

            $this->newLine();
            $this->info('Test Scans to be deleted:');
            $this->table(
                ['ID', 'Type', 'Command', 'Status', 'Created'],
                $testScans->map(function ($scan) {
                    return [
                        $scan->id,
                        $scan->scan_type,
                        $scan->command,
                        $scan->status,
                        $scan->created_at->format('Y-m-d H:i:s'),
                    ];
                })->toArray()
            );
        } else {
            if (! $force && ! $this->confirm('Are you sure you want to delete these test records?')) {
                $this->info('Cleanup cancelled');

                return 0;
            }

            $deletedEvents = 0;
            $deletedScans = 0;

            DB::transaction(function () use ($testEvents, $testScans, &$deletedEvents, &$deletedScans) {
                // Delete test events
                foreach ($testEvents as $event) {
                    $event->delete();
                    $deletedEvents++;
                }

                // Delete test scans
                foreach ($testScans as $scan) {
                    $scan->delete();
                    $deletedScans++;
                }
            });

            $this->info("✅ Deleted {$deletedEvents} test events");
            $this->info("✅ Deleted {$deletedScans} test scans");
        }

        return 0;
    }
}
