name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  package-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2]
        laravel: [9.*, 10.*]
        exclude:
          - php: 8.1
            laravel: 10.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/pest

  integration-test:
    runs-on: ubuntu-latest
    name: Integration Test
    needs: package-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Create Laravel application
        run: |
          composer create-project laravel/laravel:^9.0 laravel-app
          cd laravel-app
          composer config repositories.local '{"type": "path", "url": "../", "options": {"symlink": true}}'
          composer require prahsys/laravel-perimeter:@dev

      - name: Publish config
        run: |
          cd laravel-app
          php artisan vendor:publish --provider="Prahsys\Perimeter\PerimeterServiceProvider" --tag=perimeter-config

      - name: Run health check
        run: |
          cd laravel-app
          php artisan perimeter:health
          
      - name: Install perimeter (where possible)
        continue-on-error: true
        run: |
          cd laravel-app
          sudo php artisan perimeter:install --no-interaction || echo "Skipping full installation in CI environment"

  docker-test:
    runs-on: ubuntu-latest
    name: Docker Container Test
    needs: package-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker container
        run: |
          docker-compose build
          docker-compose up -d
          docker ps

      - name: Run health check in container
        run: |
          docker exec prahsys-laravel-perimeter php artisan perimeter:health
          
      - name: Install security components (non-interactive)
        run: |
          docker exec prahsys-laravel-perimeter sudo php artisan perimeter:install --no-interaction
          
      - name: Run health check again after installation
        run: |
          docker exec prahsys-laravel-perimeter php artisan perimeter:health
          
      - name: Tear down containers
        run: docker-compose down